# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmIzMzUzMGI3ZDg0YjliNDk4ZDA2MjgyMzY4MzM1YmM3MDllMzVlYTM5NDc5NDVhMWVmMjQ1MzQxMTM0ZmY3ZDhjMzhhYzI4YmNhMDBiODU4MDg1NGE2NWQzMTFkOGI1YmM3YmY1YmZkNWZhOWJhMTQ3MWNhNTNjYmNjZTI0NDc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
